apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging
  namespace: argocd
spec:
  project: cluster-management
  source:
    repoURL: https://github.com/redhat-mal/argocd-examples.git
    targetRevision: master
    path: ocp-cluster-management
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-logging
